name: 'Programmable Banking Card code Action'
description: 'Runs card code in an emulated environment'
inputs:
  payments-file:  # id of input
    description: 'Payment File'
    required: true
    default: 'payments.yml'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'